name: Publish

on:
  push:
    tags: 
    - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      run: cargo test --verbose

    - name: Publish
      run: cargo publish --token ${CRATES_TOKEN}
    env:
        CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
